USE [gzglz]
GO

/****** Object:  Table [dbo].[Station_Common]    Script Date: 2017/12/20 13:12:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Station_Common](
	[station_id] [varchar](10) NOT NULL,
	[staname] [nvarchar](20) NOT NULL,
	[station_style] [nvarchar](50) NULL,
	[Longitude] [float] NULL,
	[Latitude] [float] NULL,
	[Altitude] [float] NULL,
	[Station_used] [float] NULL,
	[Identifier] [nvarchar](50) NULL,
	[telephone] [varchar](20) NULL,
	[Net_select] [varchar](20) NULL,
	[Comm_mode] [varchar](20) NULL,
	[Upload_or_not] [int] NULL,
	[Upload_interval] [int] NULL,
	[Upload_filepath] [varchar](50) NULL,
	[Txt_filepath] [varchar](150) NULL,
	[Measure_zone] [varchar](20) NULL,
	[Check_station] [varchar](20) NULL,
	[Data_center_ip] [varchar](20) NULL,
	[Data_center_interval] [varchar](20) NULL,
	[Data_center_port] [varchar](20) NULL,
	[Data_center_username] [varchar](20) NULL,
	[Data_center_password] [varchar](20) NULL,
	[Data_center_filepath] [varchar](20) NULL,
	[Net_center_ip] [varchar](20) NULL,
	[Net_center_interval] [varchar](20) NULL,
	[Net_center_port] [varchar](20) NULL,
	[Net_center_username] [varchar](20) NULL,
	[Net_center_password] [varchar](20) NULL,
	[Net_center_filepath] [varchar](20) NULL,
	[Comm_txfs] [varchar](20) NULL,
	[Comm_number] [varchar](20) NULL,
	[Comm_interval] [varchar](20) NULL,
	[Embedded_depth_1] [varchar](20) NULL,
	[Embedded_depth_2] [varchar](20) NULL,
	[Embedded_depth_3] [varchar](20) NULL,
	[Embedded_depth_4] [varchar](20) NULL,
	[Embedded_depth_5] [varchar](20) NULL,
	[Embedded_depth_6] [varchar](20) NULL,
	[Embedded_depth_7] [varchar](20) NULL,
	[Embedded_depth_8] [varchar](20) NULL,
	[Sensor_used_1] [varchar](20) NULL,
	[Sensor_used_2] [varchar](20) NULL,
	[Sensor_used_3] [varchar](20) NULL,
	[Sensor_used_4] [varchar](20) NULL,
	[Sensor_used_5] [varchar](20) NULL,
	[Sensor_used_6] [varchar](20) NULL,
	[Sensor_used_7] [varchar](20) NULL,
	[Sensor_used_8] [varchar](20) NULL,
	[Correction_value_1] [varchar](20) NULL,
	[Correction_value_2] [varchar](20) NULL,
	[Correction_value_3] [varchar](20) NULL,
	[Correction_value_4] [varchar](20) NULL,
	[Correction_value_5] [varchar](20) NULL,
	[Correction_value_6] [varchar](20) NULL,
	[Correction_value_7] [varchar](20) NULL,
	[Correction_value_8] [varchar](20) NULL,
	[User_defined_curve_1] [varchar](200) NULL,
	[User_defined_curve_2] [varchar](200) NULL,
	[User_defined_curve_3] [varchar](200) NULL,
	[User_defined_curve_4] [varchar](200) NULL,
	[User_defined_curve_5] [varchar](200) NULL,
	[User_defined_curve_6] [varchar](200) NULL,
	[User_defined_curve_7] [varchar](200) NULL,
	[User_defined_curve_8] [varchar](200) NULL,
	[Soil_texture_1] [varchar](20) NULL,
	[Soil_texture_2] [varchar](20) NULL,
	[Soil_texture_3] [varchar](20) NULL,
	[Soil_texture_4] [varchar](20) NULL,
	[Soil_texture_5] [varchar](20) NULL,
	[Soil_texture_6] [varchar](20) NULL,
	[Soil_texture_7] [varchar](20) NULL,
	[Soil_texture_8] [varchar](20) NULL,
	[Soil_bulk_denslty_1] [varchar](20) NULL,
	[Soil_bulk_denslty_2] [varchar](20) NULL,
	[Soil_bulk_denslty_3] [varchar](20) NULL,
	[Soil_bulk_denslty_4] [varchar](20) NULL,
	[Soil_bulk_denslty_5] [varchar](20) NULL,
	[Soil_bulk_denslty_6] [varchar](20) NULL,
	[Soil_bulk_denslty_7] [varchar](20) NULL,
	[Soil_bulk_denslty_8] [varchar](20) NULL,
	[field_capacity_1] [varchar](20) NULL,
	[field_capacity_2] [varchar](20) NULL,
	[field_capacity_3] [varchar](20) NULL,
	[field_capacity_4] [varchar](20) NULL,
	[field_capacity_5] [varchar](20) NULL,
	[field_capacity_6] [varchar](20) NULL,
	[field_capacity_7] [varchar](20) NULL,
	[field_capacity_8] [varchar](20) NULL,
	[Fade_Moisture_1] [varchar](20) NULL,
	[Fade_Moisture_2] [varchar](20) NULL,
	[Fade_Moisture_3] [varchar](20) NULL,
	[Fade_Moisture_4] [varchar](20) NULL,
	[Fade_Moisture_5] [varchar](20) NULL,
	[Fade_Moisture_6] [varchar](20) NULL,
	[Fade_Moisture_7] [varchar](20) NULL,
	[Fade_Moisture_8] [varchar](20) NULL,
	[Sensor_used_9] [varchar](20) NULL,
	[Gr_parameter] [varchar](20) NULL,
	[Pr_parameter] [varchar](20) NULL,
	[Co2_parameter] [varchar](20) NULL,
	[CanopyTemp_MC0] [varchar](20) NULL,
	[CanopyTemp_MC1] [varchar](20) NULL,
	[CanopyTemp_MC2] [varchar](20) NULL,
	[CanopyTemp_BC0] [varchar](20) NULL,
	[CanopyTemp_BC1] [varchar](20) NULL,
	[CanopyTemp_BC2] [varchar](20) NULL,
	[WDirection_used] [varchar](20) NULL,
	[WSpeed1_used] [varchar](20) NULL,
	[WSpeed2_used] [varchar](20) NULL,
	[Temperature1_used] [varchar](20) NULL,
	[Temperature2_used] [varchar](20) NULL,
	[Hum1_used] [varchar](20) NULL,
	[Hum2_used] [varchar](20) NULL,
	[GR_used] [varchar](20) NULL,
	[PR_used] [varchar](20) NULL,
	[WaterTemp_used] [varchar](20) NULL,
	[CanopyTemp_used] [varchar](20) NULL,
	[Co2_used] [varchar](20) NULL,
	[SurTemp_used] [varchar](20) NULL,
	[GTemp1_used] [varchar](20) NULL,
	[GTemp2_used] [varchar](20) NULL,
	[Rain_used] [varchar](20) NULL,
	[AirPressure_used] [nchar](10) NULL,
	[PRL1_used] [nchar](10) NULL,
	[PRL2_used] [nchar](10) NULL,
	[PRL3_used] [nchar](10) NULL,
	[Temperature3_used] [nchar](10) NULL,
	[TemperatureL1_used] [nchar](10) NULL,
	[TemperatureL2_used] [nchar](10) NULL,
	[TemperatureL3_used] [nchar](10) NULL,
	[HumL1_used] [nchar](10) NULL,
	[HumL2_used] [nchar](10) NULL,
	[HumL3_used] [nchar](10) NULL,
	[SoilWater1_used] [nchar](10) NULL,
	[SoilWater2_used] [nchar](10) NULL,
	[SoilWater3_used] [nchar](10) NULL,
	[SoilWater4_used] [nchar](10) NULL,
	[SoilWater5_used] [nchar](10) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


